;;; undo-tree-test.el --- Tests for undo-tree
(ert-deftest undo-tree-test/undo ()
  "Simple undo works for insertion and deletion"
    (with-temp-buffer
      (buffer-enable-undo)
      (undo-tree-mode 1)
      (insert "1234567890")
      (undo-boundary)
      (goto-char 5)
      (insert "abcd")
      (undo-boundary)
      (should (string-equal "1234abcd567890" (buffer-string)))
      (undo-tree-undo)
      (should (string-equal "1234567890" (buffer-string)))
      (undo-tree-redo)
      (should (string-equal "1234abcd567890" (buffer-string)))
      ))

(ert-deftest undo-tree-test/undo-tree-size ()
  "Simple undo-tree size tests"
  (with-temp-buffer
    (buffer-enable-undo)
    (undo-tree-mode 1)
    (insert "1234567890")
    (undo-boundary)
    (goto-char 5)
    (insert "abcd")
    (undo-boundary)
    (undo-list-transfer-to-tree)
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    (undo-tree-undo)
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    (undo-tree-redo)
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    ))

(ert-deftest undo-tree-test/undo-tree-size-1 ()
  "More undo-tree size tests"
  (with-temp-buffer
    (buffer-enable-undo)
    (undo-tree-mode 1)
    (undo-tree-test-setup)
    (dotimes (_ 20)
      (goto-char (point-min))
      (replace-string "lorem" "dignissim-")
      (undo-boundary)
      (goto-char (point-min))
      (replace-string "dignissim-" "lorem--")
      (undo-boundary)
      (goto-char (point-min))
      (replace-string "lorem--" "dignissim---")
      (undo-boundary)
      (goto-char (point-min))
      (replace-string "dignissim---" "lorem")
      (undo-boundary))
    (undo-list-transfer-to-tree)
    ;; (should (string-equal "(nil undo-tree-canary)" (format "%s" buffer-undo-list)))
    ;; (should (string-equal "t" "nil"))
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    ;; (should (string-equal "t" "nil"))
    (undo-tree-print-undo-tree)
    (undo-tree-undo 60)
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    (undo-tree-redo 40)
    (should (equal (undo-tree-calc-tree-size (undo-tree-root buffer-undo-tree))
                   (undo-tree-size buffer-undo-tree)))
    ))

(ert-deftest undo-tree-test/undo-tree-simple-tree ()
  "Simple undo-tree size tests"
  (with-temp-buffer
    (buffer-enable-undo)
    (undo-tree-mode 1)
    (insert "1234567890")
    (undo-boundary)
    (should (string-equal (buffer-string) "1234567890"))

    (goto-char 5)
    (insert "abcd")
    (undo-boundary)
    (should (string-equal (buffer-string) "1234abcd567890"))

    (goto-char 10)
    (insert "qwerty")
    (undo-boundary)
    (should (string-equal (buffer-string) "1234abcd5qwerty67890"))

    (undo-tree-undo 1)
    (should (string-equal (buffer-string) "1234abcd567890"))

    (goto-char 0)
    (insert "0987")
    (undo-boundary)
    (should (string-equal (buffer-string) "09871234abcd567890"))

    (undo-tree-undo 1)
    (should (string-equal (buffer-string) "1234abcd567890"))

    (undo-tree-switch-branch 1)
    (undo-tree-redo 1)
    (should (string-equal (buffer-string) "1234abcd5qwerty67890"))
    (should (equal (undo-tree-calc-tree-size buffer-undo-tree)
                   (undo-tree-size buffer-undo-tree)))
    ))

;; TODO: add test for GCed undo-tree
;;; undo-tree-test.el ends here
